@startuml

class User {
  + id: uuid
  + OKnickname: String
  + OKemail: String
  + OKcpf: number
  + OKpassword: String
  + OKemailVerified: boolean
  + createdAt: Date
  + updatedAt: Date
  + Trainings: Training[]
  + newPasswordCodes: NewPasswordCode[]
  + workoutHistory: WorkoutHistory[]
  + goals: Goals[]
  + bodyData: BodyData[]
  + performanceEvaluations: PerformanceEvaluation[]
}

@enduml