@startuml DiagramName

class User {
  + id: uuid
  + nickname: String
  + email: String
  + password: String
  + emailVerified: boolean
  + createdAt: Date
  + updatedAt: Date
  + trainings: Training[]
  }

@enduml