@startuml DiagramName
left to right direction

actor User as u

package "Exercise" {
  usecase "Criar Exercício" as UC1 <<User cria um novo exercício>>

  usecase "Atualizar Exercício" as UC2 <<User atualiza informações de um exercício existente>>

  usecase "Excluir Exercício" as UC3 <<User exclui um exercício existente>>

  usecase "Obter Informações do Exercício" as UC4 <<User obtém informações detalhadas sobre um exercício>>

  usecase "Listar Exercícios" as UC5 <<User lista todos os exercícios disponíveis>>

  usecase "Pesquisar Exercícios" as UC6 <<User busca exercícios por palavras-chave>>

  usecase "Adicionar Exercício ao Treinamento" as UC7 <<User inclui um exercício em um programa de treinamento específico>>

  usecase "Visualizar Estatísticas do Exercício" as UC8 <<User verifica estatísticas relacionadas a um exercício>>

}

u --> UC1
u --> UC2
u --> UC3
u --> UC4
u --> UC5
u --> UC6
u --> UC7
u --> UC8

@enduml
