@startuml DiagramName

class User {
  + id: uuid
  + nickname: String
  + email: String
  + password: String
  + emailVerified: boolean
  + createdAt: Date
  + updatedAt: Date
  + login(): void
  + verifyEmail(): void
  + createAccount(): void
  + deleteAccount(): void
  + updateAccount(): void
  + changePassword(): void
  + trainings: Training[]
  }

class Exercise {
  + id: uuid
  + createdAt: Date
  + updatedAt: Date
  + name: String
  + description: String
  + category: String
  + restTime: number
  + weight: number
  + repetitions: number
  + series: number
  + createExercise(): void
  + updateExercise(): void
  + deleteExercise(): void
  + getExercise(): void
}

class Training {
  + id: uuid
  + name: String
  + active: boolean
  + exercises: Exercise[]
}



User --> Exercise : cria
Exercise --|> Training : inclui

@enduml