@startuml

actor User as u

u -> Exercise : Cria um novo exercício
u -> NewPasswordCode : Solicita troca de senha
NewPasswordCode -> u : Cria um código de troca de senha
u -> WorkoutHistory : Visualiza histórico de treino
u -> BodyData : Registra peso e medidas
BodyData -> u : Visualiza progresso
PerformanceEvaluation -> u : Avalia desempenho
PerformanceEvaluation -> u : Sugere melhorias
WorkoutHistory -> PerformanceEvaluation : Fornece historico de treino
Exercise --|> Training : Inclui no programa de treinamento

@enduml
