@startuml DiagramName

class User {
  + id: uuid
  + nickname: String
  + email: String
  + password: String
  + emailVerified: boolean
  + createdAt: Date
  + updatedAt: Date
  + login(): void
  + verifyEmail(): void
  + createAccount(): void
  + deleteAccount(): void
  + updateAccount(): void
  + changePassword(): void
  + trainings: Training[]
  }




User --> User : cria


@enduml