@startuml

class User {
  + id: uuid
  + nickname: String
  + email: String
  + cpf: number
  + password: String
  + emailVerified: boolean
  + createdAt: Date
  + updatedAt: Date
  + login(): void
  + verifyEmail(): void
  + createAccount(): void
  + deleteAccount(): void
  + updateAccount(): void
  + changePassword(): void
  + exercises: Exercise[]
  
}

class Exercise {
  + id: uuid
  + createdAt: Date
  + updatedAt: Date
  + name: String
  + description: String
  + category: String
  + restTime: number
  + weight: number
  + repetitions: number
  + series: number
  + createExercise(): void
  + updateExercise(): void
  + deleteExercise(): void
  + getExercise(): void
}


User --> Exercise : cria


@enduml