@startuml
left to right direction

actor User as u

package "WeightAndMeasurements" {
  usecase "Record Weight and Measurements" as UC1 <<User logs their current weight and body measurements>>

  usecase "View Progress" as UC2 <<User views progress based on recorded weight and measurements>>

  usecase "Set Goals" as UC3 <<User sets specific goals for weight and measurements>>

  usecase "Track Goal Progress" as UC4 <<User tracks the progress toward their set goals>>

  usecase "Delete Record" as UC5 <<User deletes a recorded entry of weight and measurements>>

}

u --> UC1
u --> UC2
u --> UC3
u --> UC4
u --> UC5

@enduml