@startuml
left to right direction

actor User as u

package "WorkoutHistory" {
  usecase "Visualizar Histórico de Treino" as UC1 <<O User revisa e examina seus dados históricos de treino>>

  usecase "Filtrar Histórico de Treino" as UC2 <<O User filtra o histórico de treino com base em critérios específicos>>

  usecase "Exportar Histórico de Treino" as UC3 <<O User exporta o histórico de treino para análise ou registro>>

  usecase "Compartilhar Histórico de Treino" as UC4 <<O User compartilha o histórico de treino com outras pessoas>>

  usecase "Excluir Entrada de Treino" as UC5 <<O User exclui uma entrada específica do histórico de treino>>

}

u --> UC1
u --> UC2
u --> UC3
u --> UC4
u --> UC5

@enduml
