@startuml DiagramName
left to right direction

actor User as u

package "User" {
  usecase "login()OK" as UC1 <<O User inicia o processo de login para acessar o sistema>>

  usecase "verifyEmail()OK" as UC2 <<O User confirma e valida seu endereço de e-mail>>

  usecase "createAccount()OK" as UC3 <<O User estabelece uma nova conta no sistema>>

  usecase "deleteAccount()OK" as UC4 <<O User remove permanentemente sua conta do sistema>>

  usecase "updateAccount()OK" as UC5 <<O User modifica e atualiza as informações da sua conta>>

  usecase "changePassword()OK" as UC6 <<O User altera a senha da sua conta por razões de segurança>>

  usecase "listTraining()" as UC7 <<O User explora e observa os programas de treinamento disponíveis>>

  usecase "emitNewPassword()" as UC8 <<O User inicia um processo para redefinir ou recuperar sua senha>>

  usecase "viewTrainingHistory()" as UC9 <<O User revisa e examina seus dados históricos de treino>>

  usecase "recordBodyData()" as UC10 <<O User registra seu peso atual e medidas corporais>>

  usecase "evaluatePerformance()" as UC11 <<O User avalia e analisa suas métricas de desempenho>>
}

u --> UC1
u --> UC2
u --> UC3
u --> UC4
u --> UC5
u --> UC6
u --> UC7
u --> UC8
u --> UC9
u --> UC10
u --> UC11
@enduml
