@startuml DiagramName
left to right direction

actor User as u

package "User" {
  usecase "login()OK" as UC1 <<O User inicia o processo de login para acessar o sistema>>

  usecase "verifyEmail()OK" as UC2 <<O User confirma e valida seu endereço de e-mail>>

  usecase "createAccount()OK" as UC3 <<O User estabelece uma nova conta no sistema>>

  usecase "deleteAccount()OK" as UC4 <<O User remove permanentemente sua conta do sistema>>

  usecase "updateAccount()OK" as UC5 <<O User modifica e atualiza as informações da sua conta>>

  usecase "changePassword()OK" as UC6 <<O User altera a senha da sua conta por razões de segurança>>

  usecase "emitNewPassword()" as UC7 <<O User inicia um processo para redefinir ou recuperar sua senha>>

}

u --> UC1
u --> UC2
u --> UC3
u --> UC4
u --> UC5
u --> UC6
u --> UC7
@enduml
