@startuml
left to right direction

actor User as u

package "NewPasswordCode" {
  usecase "Criar Novo Código de Senha" as UC1 <<User cria um novo código para redefinir sua senha>>

  usecase "Excluir Código de Senha" as UC2 <<User exclui um código existente de redefinição de senha>>

  usecase "Verificar Código de Senha" as UC3 <<User verifica a validade de um código de redefinição de senha>>

  usecase "Reenviar Código de Senha" as UC4 <<User solicita o reenvio do código de redefinição de senha>>

  usecase "Estender Expiração do Código" as UC5 <<User estende o tempo de expiração de um código de redefinição de senha>>

}

u --> UC1
u --> UC2
u --> UC3
u --> UC4
u --> UC5

@enduml
